# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Workflow 

on:
  push:
    branches: [ "master" ]
    
env:
  REMOTE_HOST: 15.207.85.142
  REMOTE_USER: ec2-user
  
permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present 
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/github-actions-key
        chmod 600 ~/.ssh/github-actions-key
        cat >>~/.ssh/config <<END
        Host ec2
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/github-actions-key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ env.REMOTE_HOST }}
        SSH_USER: ${{ env.REMOTE_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }} 
        
    - name: Copy files to directory in EC2
      run: scp -r dist/* ec2:/var/www/portfolio.com 
